Separate Argo CD application deployment

diff --git a/.github/workflows/infrastructureAKS.yml b/.github/workflows/infrastructureAKS.yml
--- a/.github/workflows/infrastructureAKS.yml
+++ b/.github/workflows/infrastructureAKS.yml
@@ -52,7 +52,7 @@ jobs:
 
 
   kubernetes:
-    name: Terraform Kubernetes - NGINX + Argo CD
+    name: Terraform Kubernetes - NGINX 
     runs-on: ubuntu-latest
 
     needs:
@@ -66,7 +66,7 @@ jobs:
 
       - name: Checkout repository
         uses: actions/checkout@v4
-        
+
       - name: Azure Setup
         uses: ./.github/actions/azure-setup
 
@@ -89,3 +89,59 @@ jobs:
         run: terraform apply -auto-approve
 
 
+  argocd-application:
+    name: Terraform - Argo CD Application
+    runs-on: ubuntu-latest
+
+    needs:
+      - kubernetes
+
+    defaults:
+      run:
+        working-directory: terraform/argocd-app
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Azure Setup
+        uses: ./.github/actions/azure-setup
+
+      - name: Get AKS credentials
+        run: |
+          az aks get-credentials \
+            --resource-group rg-aks-cuestionario \
+            --name aks-cuestionario \
+            --overwrite-existing
+
+      - name: Wait for Argo CD Application CRD
+        shell: bash
+        run: |
+          echo "Esperando al CRD applications.argoproj.io..."
+
+          for i in $(seq 1 60); do
+            if kubectl get crd applications.argoproj.io >/dev/null 2>&1; then
+              echo "CRD Application disponible."
+              exit 0
+            fi
+
+            sleep 10
+          done
+
+          echo "ERROR: el CRD no apareció en 10 minutos."
+          exit 1
+
+      - name: Terraform Init
+        run: terraform init
+
+      - name: Terraform Format Check
+        run: terraform fmt -check -recursive
+
+      - name: Terraform Validate
+        run: terraform validate
+
+      - name: Terraform Plan
+        run: terraform plan
+
+      - name: Terraform Apply
+        run: terraform apply -auto-approve
